kind: pipeline
name: Firefly-III-MainImage-Synology
type: docker

trigger:
  event:
    - custom

steps:
  - name: 'Build!'
    image: plugins/docker
    settings:
      storage_driver: vfs # https://discourse.drone.io/t/plugins-docker-on-synology-dsm/8456/6
      dry_run: false
      registry: <your registry>
      username:
        from_secret: docker_registry_user
      password:
        from_secret: docker_registry_password
      repo: <your registry>/fireflyiii/core
      dockerfile: Dockerfile
      platform: linux/x86_64
      tags:
        - latest
        - version-6
        - version-6.0
        - version-6.0.5
      build_args:
        - LOG_LEVEL=debug
        - build_base_image=<your registry>/fireflyiii/base:apache-8.2-buster
        - version=v6.0.5
